### ISSUE TITLE
validování délky videa

### ISSUE THREAD

**Issue by magpie89** [MichaelaRasovska/VideoLibrary_Team001#4]
nevaliduje určitě časy : 6-9 vteřin / 60-89 …. 
lze zadat i jako písmeno a lze možné jít do mínusu

**Comment by PetrKoller** [comment]
Should be solved with commit https://github.com/MichaelaRasovska/VideoLibrary_Team001/commit/4f577f0ca63b3f5e02bda1a85b56626c805cb2a1
