### ISSUE TITLE
nové okno s url 

### ISSUE THREAD

**Issue by magpie89** [MichaelaRasovska/VideoLibrary_Team001#5]
Po kliknutí na url daného videoklipu, prosím, otevřít na nové kartě prohlížeče. Až budeme prezentovat, akorát by nám to "uškodilo"

**Comment by PetrKoller** [comment]
Fixed in newest commit 
https://github.com/MichaelaRasovska/VideoLibrary_Team001/commit/3a1182dc64555f6248265d00b796529efe0fb127
